### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by dorkthrone** [KingsOfXur/wherethefuckisxur#10]
When the fuck is Xur? How the fuck is Xur? Who the fuck is Xur? ETC.

**Comment by Gnarwall19** [comment]
Hey Steven I’m a fairly new developer, graduate of a coding bootcamp, and destiny fanatic. I’ve been using your site for years and would love to contribute! This seems like a fairly simple job (the FAQ) that i’d love to take on. Would that be ok?

**Comment by RogueCalypso** [comment]
I have added this page in this branch: reorganization. Includes placeholder text for now

**Comment by dorkthrone** [comment]
> Hey Steven I’m a fairly new developer, graduate of a coding bootcamp, and destiny fanatic. I’ve been using your site for years and would love to contribute! This seems like a fairly simple job (the FAQ) that i’d love to take on. Would that be ok?

@Gnarwall19 This has already been taken care of. Stick around though we'll find you some things to work on. Thanks!

**Comment by Gnarwall19** [comment]
> > Hey Steven I’m a fairly new developer, graduate of a coding bootcamp, and destiny fanatic. I’ve been using your site for years and would love to contribute! This seems like a fairly simple job (the FAQ) that i’d love to take on. Would that be ok?
> 
> @Gnarwall19 This has already been taken care of. Stick around though we'll find you some things to work on. Thanks!

Awesome I really appreciate it! Feel free to shoot me a message anytime you're looking to get something done.

**Comment by dorkthrone** [comment]
FAQ page is being put on the back burner
