### ISSUE TITLE
List the sections needed on the main page

### ISSUE THREAD

**Issue by sudomilk** [KingsOfXur/wherethefuckisxur#2]
We need to figure out exactly what shows up on the main page and kind of contain them in sections.

Here's a few to start out:

+ header
+ xur location
+ xur inventory

**Comment by dorkthrone** [comment]
I'd like to add a section, perhaps a footer, that has a brief copy blurb about this now being an open-source project (maybe we call the team "King of Xur"?). That being said I also want to remove the PayPal link for donations.

**Comment by sudomilk** [comment]
Looks good I'll close this for now.
